# railway.toml (repo-root/railway.toml)
[build]
rootDirectory = "backend"
buildCommand = "npm ci && npm run build"

[deploy]
rootDirectory = "backend"
preDeployCommand = ["node build/ace migration:run --force"]
startCommand = "node build/bin/server.js"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"